### ISSUE TITLE
Grant commit bits...

### ISSUE THREAD

**Issue by pburkholder** [paulczar/inspec-stigs#5]
Paul - this is clearly getting some traction - how about granting Jeremy (@som3guy) and me commit bits? Or should we just fork to his repo?

--Peter

**Comment by paulczar** [comment]
I'm actually wondering if we should create a GH org for it and move to that.

**Comment by jmi4** [comment]
I think a GH sounds fun, but mainly because I have not been part of a public one yet.
+1 for that.

**Comment by jmi4** [comment]
A question on this however. Should we simply push our changes or wait for a couple +1's before merging? 
At my work we always have at least 2 +1's however since there are only 3 of us here I am open to anything.
I have been doing PR's even though you gave me write permissions, as this is what I am used to.

**Comment by pburkholder** [comment]
@som3guy Closing this since we have the commit bits, the original issue, and continuing in #8
